### ISSUE TITLE
"Biocircos2 will online soon!" - Will this soon be true?

### ISSUE THREAD

**Issue by oschwengers** [YaCui/Biocircos.js#4]
Hi and thanks a lot for this very nice JS lib!

As there was no progress over the last 3 years and there is still this "Biocircos2 will online soon!" on the readme. May I ask if there this lib is still maintained?

Will we see a v2.0 somewhere?
Thanks and best regards!

**Comment by YaCui** [comment]
Hi Oschwengers,

Yes. A new version will be online soon.

Thanks,
Ya

**Comment by oschwengers** [comment]
@YaCui fantastic!
Can you provide an ETA as guidance and maybe some upfront comments of what to expect in this new version?
Thanks in advance! I'm really looking forward to the new version.

**Comment by YaCui** [comment]
> @YaCui fantastic!
> Can you provide an ETA as guidance and maybe some upfront comments of what to expect in this new version?
> Thanks in advance! I'm really looking forward to the new version.

**Comment by YaCui** [comment]
Hi Oschwengers,

Here is the link: https://wlcb.oit.uci.edu/NG-Circos. Thanks for using BioCircos/NG-Circos.

Thanks,
Ya
